//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SyndicationFeed.ReaderWriter.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFeedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFeedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SyndicationFeed.ReaderWriter.Tests.TestFeedResources", typeof(TestFeedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://contoso.com.
        /// </summary>
        internal static string ContosoUrl {
            get {
                return ResourceManager.GetString("ContosoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot; xmlns:content=&quot;http://purl.org/rss/1.0/modules/content/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;NewItem&gt;
        ///      &lt;enclosure url=&quot;http://www.scripting.com/mp3s/weatherReportSuite.mp3&quot; length=&quot;12216320&quot; type=&quot;audio/mpeg&quot; /&gt;
        ///      &lt;title&gt;&lt;![CDATA[Lorem ipsum 2017-07-06T20:25:00+00:00]]&gt;&lt;/title&gt;
        ///      &lt;description&gt;&lt;![CDATA[Exercitation sit dolore mollit et est eiusmod veniam aute offici [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomXml {
            get {
                return ResourceManager.GetString("CustomXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://contoso.com/syndication/feed/examples.
        /// </summary>
        internal static string ExampleNs {
            get {
                return ResourceManager.GetString("ExampleNs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://example.com/permalink/example/1523389.
        /// </summary>
        internal static string ExampleUrl {
            get {
                return ResourceManager.GetString("ExampleUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/dotnet/SyndicationFeedReaderWriter.
        /// </summary>
        internal static string GithubUrl {
            get {
                return ResourceManager.GetString("GithubUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;rss xmlns:content=&quot;http://purl.org/rss/1.0/modules/content/&quot; xmlns:media=&quot;http://search.yahoo.com/mrss/&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///    &lt;title&gt;NDTV News  - Latest&lt;/title&gt;
        ///    &lt;link&gt;http://www.ndtv.com/&lt;/link&gt;
        ///    &lt;lastBuildDate&gt;August 03, 2017 02:50 AM&lt;/lastBuildDate&gt;
        ///    &lt;newsAppVersion&gt;0.6&lt;/newsAppVersion&gt;
        ///    &lt;timezone&gt;GMT+05:30&lt;/timezone&gt;
        ///    &lt;recordcount&gt;200&lt;/recordcount&gt;
        ///    
        ///    &lt;atom10:link xmlns:atom10=&quot;http://www.w3.org/2005/Atom&quot; rel=&quot;self&quot; type= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string internetRssFeed {
            get {
                return ResourceManager.GetString("internetRssFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss xmlns:atom=&quot;http://www.w3.org/2005/Atom&quot; xmlns:content=&quot;http://purl.org/rss/1.0/modules/content/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; version=&quot;2.0&quot;&gt;
        ///   &lt;channel&gt;
        ///      &lt;author&gt;abc@def.com (John Doe)&lt;/author&gt;
        ///      &lt;title asd=&quot;123&quot;&gt;&lt;![CDATA[Lorem ipsum feed for an interval of 1 minutes]]&gt;&lt;/title&gt;
        ///      &lt;description&gt;&lt;![CDATA[This is a constantly updating lorem ipsum feed]]&gt;&lt;/description&gt;
        ///      &lt;link length=&quot;123&quot; type=&quot;testType&quot; &gt;http://example.com/&lt;/li [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rss20 {
            get {
                return ResourceManager.GetString("rss20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;rss xmlns:example=&quot;http://contoso.com/syndication/feed/examples&quot; version=&quot;2.0&quot;&gt;
        ///   &lt;channel&gt;
        ///      &lt;title asd=&quot;123&quot;&gt;&lt;![CDATA[Lorem ipsum feed for an interval of 1 minutes]]&gt;&lt;/title&gt;
        ///      &lt;description&gt;&lt;![CDATA[This is a constantly updating lorem ipsum feed]]&gt;&lt;/description&gt;
        ///      &lt;link length=&quot;123&quot; type=&quot;testType&quot; &gt;http://example.com/&lt;/link&gt;
        ///      &lt;image&gt;
        ///        &lt;url&gt;http://2.bp.blogspot.com/-NA5Jb-64eUg/URx8CSdcj_I/AAAAAAAAAUo/eCx0irI0rq0/s1600/bg_Microsoft_lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string rss20_2items {
            get {
                return ResourceManager.GetString("rss20_2items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss xmlns:example=&quot;http://contoso.com/syndication/feed/examples&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;channel&gt;
        ///  &lt;item&gt;
        ///    &lt;title&gt;Rss Writer Available&lt;/title&gt;
        ///    &lt;description&gt;The new RSS Writer is now open source!&lt;/description&gt;
        ///    &lt;author&gt;test@mail.com&lt;/author&gt;
        ///    &lt;category&gt;Technology&lt;/category&gt;
        ///    &lt;guid isPermaLink=&quot;false&quot;&gt;https://github.com/dotnet/wcf/tree/lab/lab/src/Microsoft.SyndicationFeed/src&lt;/guid&gt;
        ///    &lt;pubDate&gt;Mon, 01 Jan 2024 14:44:25 GMT&lt;/pubDate&gt;
        ///    &lt;example: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RssFormatterWriterWithNamespacesResult {
            get {
                return ResourceManager.GetString("RssFormatterWriterWithNamespacesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;feed xmlns=&quot;http://www.w3.org/2005/Atom&quot; xmlns:atom10=&quot;http://www.w3.org/2005/Atom&quot;&gt;
        ///  &lt;title type=&quot;text&quot;&gt;dive into mark&lt;/title&gt;
        ///  &lt;subtitle type=&quot;html&quot;&gt;
        ///    A &amp;lt;em&amp;gt;lot&amp;lt;/em&amp;gt; of effort
        ///    went into making this effortless
        ///  &lt;/subtitle&gt;
        ///  &lt;author&gt;
        ///    &lt;name&gt;Mark Pilgrim&lt;/name&gt;
        ///    &lt;uri&gt;http://example.org/&lt;/uri&gt;
        ///    &lt;email&gt;f8dy@example.com&lt;/email&gt;
        ///  &lt;/author&gt;
        ///  &lt;contributor&gt;
        ///    &lt;name&gt;Sam Ruby&lt;/name&gt;
        ///  &lt;/contributor&gt;
        ///
        ///  &lt;atom10:category term=&quot;s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string simpleAtomFeed {
            get {
                return ResourceManager.GetString("simpleAtomFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;rss xmlns:a10=&quot;http://www.w3.org/2005/Atom&quot; version=&quot;2.0&quot;&gt;
        ///  &lt;channel xml:base=&quot;http://mypage.com/&quot;&gt;
        ///    &lt;title&gt;Microsoft News&lt;/title&gt;
        ///    &lt;link&gt;http://www.microsoft.com/news&lt;/link&gt;
        ///    &lt;category&gt;My new category&lt;/category&gt;
        ///    &lt;description&gt;&amp;lt;div&amp;gt;Most recent news from Microsoft&amp;lt;/div&amp;gt;&lt;/description&gt;
        ///    &lt;managingEditor&gt;jerry@microsoft.com&lt;/managingEditor&gt;
        ///    &lt;lastBuildDate&gt;Mon, 19 Jun 2017 11:52:39 -0700&lt;/lastBuildDate&gt;
        ///    &lt;image&gt;
        ///      &lt;url&gt;http:/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleRssFeed {
            get {
                return ResourceManager.GetString("SimpleRssFeed", resourceCulture);
            }
        }
    }
}
