//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SyndicationFeed.ReaderWriter.Tests.Rss {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RssFormatterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RssFormatterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SyndicationFeed.ReaderWriter.Tests.Rss.RssFormatterResources", typeof(RssFormatterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;comments&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateCommentsBasic {
            get {
                return ResourceManager.GetString("CreateCommentsBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;description&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ADescription&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateContentWithDescriptionOnly {
            get {
                return ResourceManager.GetString("CreateContentWithDescriptionOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;description&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ADescription&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateContentWithTitleDescription {
            get {
                return ResourceManager.GetString("CreateContentWithTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateContentWithTitleOnly {
            get {
                return ResourceManager.GetString("CreateContentWithTitleOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;enclosure&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;length&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;1234&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;type&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;AMediaType&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateEnclosureBasic {
            get {
                return ResourceManager.GetString("CreateEnclosureBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;link&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateLinkBasic {
            get {
                return ResourceManager.GetString("CreateLinkBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;link&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;ATitle&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;length&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;1234&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkBasicWithLength {
            get {
                return ResourceManager.GetString("CreateLinkBasicWithLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;link&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;type&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;AMediaType&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkBasicWithMediaType {
            get {
                return ResourceManager.GetString("CreateLinkBasicWithMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;link&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;ATitle&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;type&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;AMediaType&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;length&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;1234&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkBasicWithMediaTypeAndLength {
            get {
                return ResourceManager.GetString("CreateLinkBasicWithMediaTypeAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Test&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateLinkWithLinkTypeTest {
            get {
                return ResourceManager.GetString("CreateLinkWithLinkTypeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Test&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;ATitle&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;length&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;1234&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkWithLinkTypeTestAndLength {
            get {
                return ResourceManager.GetString("CreateLinkWithLinkTypeTestAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Test&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;type&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;AMediaType&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkWithLinkTypeTestAndMediaType {
            get {
                return ResourceManager.GetString("CreateLinkWithLinkTypeTestAndMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Test&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;ATitle&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;type&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;AMediaType&quot;
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;length&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;1234&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkWithLinkTypeTestAndMediaTypeAndLength {
            get {
                return ResourceManager.GetString("CreateLinkWithLinkTypeTestAndMediaTypeAndLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;link&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;ATitle&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateLinkWithTitle {
            get {
                return ResourceManager.GetString("CreateLinkWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;source&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string CreateSourceBasic {
            get {
                return ResourceManager.GetString("CreateSourceBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;source&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateSourceWithEmptyTitle {
            get {
                return ResourceManager.GetString("CreateSourceWithEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;source&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: &quot;ATitle&quot;,
        ///  &quot;Fields&quot;: [],
        ///  &quot;Attributes&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;url&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://contoso.com/podcast&quot;
        ///    }
        ///  ]
        ///}.
        /// </summary>
        internal static string CreateSourceWithTitle {
            get {
                return ResourceManager.GetString("CreateSourceWithTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;category&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;Technology&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string WithCategory {
            get {
                return ResourceManager.GetString("WithCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;link&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;Test title&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: [
        ///        {
        ///          &quot;Name&quot;: &quot;url&quot;,
        ///          &quot;Namespace&quot;: null,
        ///          &quot;Value&quot;: &quot;http://contoso.com/&quot;
        ///        },
        ///        {
        ///          &quot;Name&quot;: &quot;type&quot;,
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WithContosoLink {
            get {
                return ResourceManager.GetString("WithContosoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;managingEditor&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;managingeditor@contoso.com (managingeditor)&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string WithContributor {
            get {
                return ResourceManager.GetString("WithContributor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;link&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://github.com/dotnet/SyndicationFeedReaderWriter&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string WithGithubLink {
            get {
                return ResourceManager.GetString("WithGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;guid&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;AnId&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: [
        ///        {
        ///          &quot;Name&quot;: &quot;isPermaLink&quot;,
        ///          &quot;Namespace&quot;: null,
        ///          &quot;Value&quot;: &quot;false&quot;
        ///        }
        ///      ]
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string WithId {
            get {
                return ResourceManager.GetString("WithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;guid&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://example.com/permalink/example/1523389&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string WithPermalinkAndId {
            get {
                return ResourceManager.GetString("WithPermalinkAndId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;item&quot;,
        ///  &quot;Namespace&quot;: null,
        ///  &quot;Value&quot;: null,
        ///  &quot;Fields&quot;: [
        ///    {
        ///      &quot;Name&quot;: &quot;title&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;ATitle&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    },
        ///    {
        ///      &quot;Name&quot;: &quot;guid&quot;,
        ///      &quot;Namespace&quot;: null,
        ///      &quot;Value&quot;: &quot;https://example.com/permalink/example/1523389&quot;,
        ///      &quot;Fields&quot;: [],
        ///      &quot;Attributes&quot;: []
        ///    }
        ///  ],
        ///  &quot;Attributes&quot;: []
        ///}.
        /// </summary>
        internal static string WithPermalinkNoId {
            get {
                return ResourceManager.GetString("WithPermalinkNoId", resourceCulture);
            }
        }
    }
}
